### ISSUE TITLE
Check for Form Assignment before Notifications

### ISSUE THREAD

**Issue by spencerfinnell** [Astoundify/wp-job-manager-contact-listing#10]
I was having the same problem. The form used by Job Manager was working correctly but other forms weren't. Here's my solution:

- Open the file cf7.php located in /wp-content/plugins/wp-job-manager-contact-listing/includes/forms

- Locate the line: if ( ! array_search( $cf7->id, $this->forms[ $object->post_type ] ) ) { in the function notification_email

- Above that line insert the following line: if (empty($this->forms[ $object->post_type ])) return $components;

The problem is that the function array_search expects an array but the value supplied is null when a form other than the one specified in Contact a Job Form is used.

**Comment by spencerfinnell** [comment]
https://wordpress.org/support/topic/javascript-conflict-with-contact-form-7

**Comment by JeroenSormani** [comment]
I created a Pull request; https://github.com/Astoundify/wp-job-manager-contact-listing/pull/11

This fixes two issues;
- Indefinitely loading when a assigned contact form is on a other page than a listing/resume post type.
- Indefinitely loading when on a listing page.
