### ISSUE TITLE
Remove ninja_forms_get_all_forms

### ISSUE THREAD

**Issue by spencerfinnell** [Astoundify/wp-job-manager-contact-listing#16]
http://hookr.io/functions/ninja_forms_get_all_forms/

Replace with http://docs.ninjaforms.com/customer/portal/articles/1981069-functions-ninja_forms--%3Eforms--%3Eget_all-

**Comment by adampickering** [comment]
Fatal error: Call to undefined function ninja_forms_get_all_forms() in /home/nvugteveen/public_html/nomadify.io/wp-content/plugins/wp-job-manager-contact-listing/includes/forms/ninjaforms.php on line 121

**Comment by adampickering** [comment]
I keep seeing this issue on a few sites. @benjaminprojas @spencerfinnell

**Comment by spencerfinnell** [comment]
Yeah @benjaminprojas If you could hunt this down tonight that would be great. There are are some weird backwards compatibility issues with certain versions of Ninja Forms it looks like. 

I think instead of my above commit we need to check for both the function and new class.

**Comment by benjaminprojas** [comment]
@spencerfinnell @adampickering hey guys, I'm not sure that the fatal error you are getting is in the current version.  That function has been removed completely so they must be using an older version.  However, I did add in the backwards compatibility and so it should work for older versions as well.

**Comment by adampickering** [comment]
I might have not packaged this and uploaded to wp.org could you update the
readme / changelog if it hasn't been updated and just check things over so
I can the go ahead and upload to .org
