### ISSUE TITLE
Illegal Offset in Ninja Forms

### ISSUE THREAD

**Issue by spencerfinnell** [Astoundify/wp-job-manager-contact-listing#17]
Warning: Illegal string offset 'id' in /wp-content/plugins/wp-job-manager-contact-listing/includes/forms/ninjaforms.php on line 131

**Comment by spencerfinnell** [comment]
@benjaminprojas Can you take a look on Monday?

**Comment by spencerfinnell** [comment]
https://d33v4339jhl8k0.cloudfront.net/inline/18409/20eaa07135712147b35677ba35ec4488daf9cb26/625daf4b18aac0ea4951d711a10bcd8e1d16b412/image.png

**Comment by spencerfinnell** [comment]
Perhaps https://github.com/wpninjas/ninja-forms/blob/aa610dcbd8fc6e23f3253da6c3ed5a0e5cc23d05/includes/database.php#L11 needs to be used instead.

**Comment by spencerfinnell** [comment]
And https://github.com/wpninjas/ninja-forms/blob/aa610dcbd8fc6e23f3253da6c3ed5a0e5cc23d05/includes/Admin/AddFormModal.php#L58

**Comment by benjaminprojas** [comment]
@spencerfinnell any time I tried to use `Ninja_Forms()->form()->get_forms();` I would get an error that that method didn't exist.  I'm not sure why it exists except that it must be a class or model I can't access.  Instead, I rebuilt the array similar to how it is done in the deprecated function and that seems to be working now.
