### ISSUE TITLE
Warning: Illegal string offset 'form_title'

### ISSUE THREAD

**Issue by tripflex** [Astoundify/wp-job-manager-contact-listing#18]
Opening this for a client as a courtesy as it seems Ninja Forms is just pawning off the issue and telling them to find help somewhere else:

I am using Ninja forms with the Jobify wordpress theme. I updated the Ninja forms plugin to version 2.9.48. Immediately after that I got the following error message:

```
"Warning: Illegal string offset 'form_title' in /var/sites/..../public_html/wp-content/plugins/wp-job-manager-contact-listing/includes/forms/ninjaforms.php on line 131"
```
Could you please help me with this? I contacted Ninja forms support and they told me the issue was with the WP Job Manager plugin.

**Comment by spencerfinnell** [comment]
Try the latest on `master` -- should fix it.
