### ISSUE TITLE
Ninja Forms 3 Compatibility Issues

### ISSUE THREAD

**Issue by pmgarman** [Astoundify/wp-job-manager-contact-listing#23]
`[18-Jan-2017 16:00:40 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method Ninja_Forms::forms() in /wp-content/plugins/wp-job-manager-contact-listing/includes/forms/ninjaforms.php:1`

Error appears when upgrading a Ninja Forms 2.x site to 3.x. When you do this in Ninja Forms there is an upgrade process that appears so that the forms can be upgraded. With this plugin active, clicking the button to initiate that process throws a 500 error in the AJAX response. Checking the error logs, the only error is the one above.

Deactivating the WP Job Manager Contact Listing plugin, the upgrade process works without issue.

**Comment by pmgarman** [comment]
Unfortunately I don't know if they do or not :( My assumption would be yes. I'm not super familiar with that codebase in depth as much anymore.

**Comment by adampickering** [comment]
Would you be able to take a look at this @turtlepod

**Comment by turtlepod** [comment]
I'll check it today.

**Comment by turtlepod** [comment]
Sidenote: When I upgrade NinjaForms from 2 to 3, i think the plugin fail to update version number in the option. `get_option( 'ninja_forms_version', '0.0.0' )` returns `2.9.58`

even though i already update Ninja Form to latest version `3.0.26`

Not sure why.

**Comment by turtlepod** [comment]
I'm honestly don't know how to support NinjaForms plugin.
I always get
```
Fatal error: Class 'NF_Abstracts_MergeTags' not found
```

Do they use some kind of autoload ? how do i load this class?

**Comment by spencerfinnell** [comment]
3.0 has been out for 6 months now. Perhaps it would be better to just not do anything at all if we detect they aren't using 3.0 or the forms haven't been upgraded. 

Perhaps using their const version number? https://github.com/wpninjas/ninja-forms/blob/master/ninja-forms.php#L54

**Comment by turtlepod** [comment]
I'll work on this today. It's always difficult to develop plugin support for multiple major version of a plugin.
Sorry for the delay.

Sometimes, very hard to debug and switch back and forth between plugin version, and finding the right docs for each version, etc

**Comment by turtlepod** [comment]
@spencerfinnell you are correct. I think the issue is with NinjaForms it-self.

after manually updating the option to correct NinjaForms, it's actually working fine.
```
update_option( 'ninja_forms_version', '3.0.26' );
update_option( 'ninja_forms_load_deprecated', false );
```

I create an issue in Ninja Forms GitHub repository so they can address this:
https://github.com/wpninjas/ninja-forms/issues/2391

**Comment by turtlepod** [comment]
Finally found the issue.
The NinjaForms upgrade AJAX error explained above is now solved https://github.com/Astoundify/wp-job-manager-contact-listing/commit/95cf687a03a1d9e455d2cd185463d5b72c012667
