### ISSUE TITLE
Don't Override CF7 Mail (2) Notification

### ISSUE THREAD

**Issue by spencerfinnell** [Astoundify/wp-job-manager-contact-listing#9]

**Comment by JeroenSormani** [comment]
@spencerfinnell Do you know if this is still relevant, if so can you provide some more information? Thanks!

**Comment by spencerfinnell** [comment]
Yes it is. CF7 has a `send()` method in `inlucludes/mail.php` which calls `compose()`. `send()` is called for each email (and subsequently `compose()`) which uses the same filter each time: https://github.com/Astoundify/wp-job-manager-contact-listing/blob/master/includes/forms/cf7.php#L30

So the `wpcf7_mail_components` filter is called twice and overwritten both times if the secondary mail notification is set.

A `name` argument is passed which I think contains not the form name, but the notification name, which might be able to be used to check which round we are on.

**Comment by spencerfinnell** [comment]
https://github.com/wp-plugins/contact-form-7/blob/master/includes/submission.php#L247

https://github.com/wp-plugins/contact-form-7/blob/master/includes/submission.php#L260

**Comment by JeroenSormani** [comment]
FML.

I'm searching for the right answer, trying stuff that really should work. Turns out the third parameter that is needed was just recently added and released.

Just added PR https://github.com/Astoundify/wp-job-manager-contact-listing/pull/12
Requires CF7 4.1+

**Comment by adampickering** [comment]
i'll test this out.
